---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: counter
  name: counter-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi