---
apiVersion: v1
kind: Service
metadata:
  namespace: counter
  name: counter-service
spec:
  selector:
    app: counter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
